"""add applications table and update url_groups

Revision ID: c8a33a2d50ab
Revises: d0b6baee2278
Create Date: 2025-07-18 19:18:16.959381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a33a2d50ab'
down_revision: Union[str, Sequence[str], None] = 'd0b6baee2278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('app_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('app_id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('url_groups', sa.Column('app_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('name'), table_name='url_groups')
    op.create_unique_constraint('uq_url_group_name_per_app', 'url_groups', ['name', 'app_id'])
    op.create_foreign_key(None, 'url_groups', 'applications', ['app_id'], ['app_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_groups', type_='foreignkey')
    op.drop_constraint('uq_url_group_name_per_app', 'url_groups', type_='unique')
    op.create_index(op.f('name'), 'url_groups', ['name'], unique=True)
    op.drop_column('url_groups', 'app_id')
    op.drop_table('applications')
    # ### end Alembic commands ###
